package com.emupapps.the_broker.utils;

public class Constants {
    public static final String BASE_URL = "https://aeqarat.herokuapp.com/";
    public static final String SUCCESS = "1";
    public static final String FAILED = "0";
    public static final String FIRST_INSTALL = "first_install";
    public static final String REMEMBER_ME = "remember_me";
    public static final String USER_IMAGE = "user_image";
    public static final String USERNAME = "username";
    public static final String BIRTH_DATE = "birth_date";
    public static final String ADDRESS = "address";
    public static final String EMAIL = "email";
    public static final String PHONE_NUMBER = "phone_number";
    public static final String PHONE_CODE = "phone_code";
    public static final String USER_ID = "user_id";
    public static final String USER_TYPE = "user_type";
    public static final String REAL_ESTATE_SALE = "1";
    public static final String REAL_ESTATE_RENT = "0";
    public static final String AUCTIONABLE = "1";
    public static final int SALE = 0;
    public static final int RENT = 1;
    public static final int AUCTION = 2;
    public static final int REQUEST_RENT = 0;
    public static final int REQUEST_OWNERSHIP = 1;
    public static final int REQUEST_MAINTENANCE = 2;
    public static final int REQUEST_TERMINATION = 3;
    public static final String CONTACT_OWNER = "contact_owner";
    public static final String TENANT = "tenant";
    public static final String INDIVIDUAL_OWNER = "1";
    public static final String LOCALE = "locale";
    public static final String FORGET_PASSWORD= "forget_password";
    public static final String REGISTER = "register";
    public static final String SHARED = "0";
    public static final String PRIVATE = "1";
    public static final String APPROVED = "2";
    public static final String DEFAULT = "1";
    public static final String NOT_DEFAULT = "0";
    public static final String AGENT = "3";
    public static final String HOLDER = "4";
}
